### ISSUE TITLE
domestic government health spending *new visualization*

### ISSUE THREAD

**Issue by nupur-parikh** [ONEcampaign/topic_health_financing#40]
Issue created to discuss a new visualization for section one that shows domestic government health spending as a share of total government spending.

Same groupings and time frame as all the other charts. A line chart is fine by me and in the tooltip we can show the amount in total USD and per capita if possible

**Comment by jm-rivera** [comment]
Sounds good, thanks @nupur-parikh!

Could I please have (here or on the google doc) the text for the chart?

Noted on HICs.

**Comment by nupur-parikh** [comment]
> Could I please have (here or on the google doc) the text for the chart?

Header: Government spending on health as a share of total government spending 

Chart Text: This chart shows domestic government spending on health as a share of total government spending in different countries and income levels based on World Bank income classifications. 

Chart Description: Type a country or income level in the search bar to select several countries at once. Hover over the graph to view additional details.

It is also in the google doc.
